services:
  - type: web
    name: truematch-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: 5000
      - key: FRONTEND_ORIGIN
        value: https://super-duper-acorn-pjvvgrw9j9rph67wp-5173.app.github.dev
      - key: DATABASE_URL
        value: postgresql://postgres.hpglxumzlspykverdbby:qs%3Fpcvc7BB5%2B9eP@aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
      - key: JWT_ACCESS_SECRET
        value: c2hvJtHSoG/RjpgXUNytmH9zGgs7IADX2V37yuuuqM39cdizh6PwQ1T4NjymXsEl/SW573jOng1to6IDzKvNdw==
      - key: JWT_REFRESH_SECRET
        value: /8AoHAlVLM04E85jz+KLlBh9fdImtsAh3JOIfkLCY6Q6X6I1oyCkhLwzv+VpOtB04cEiuAKKy7b+YDGE4862Qw==
      - key: ACCESS_TOKEN_EXPIRES_IN
        value: 15m
      - key: REFRESH_TOKEN_EXPIRES_IN
        value: 7d
      - key: SMTP_HOST
        value: smtp.zoho.com
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USER
        value: noreply@truematch.chat
      - key: SMTP_PASS
        value: vpgx6VfYrdMf
      - key: SMTP_FROM_EMAIL
        value: noreply@truematch.chat
      - key: SMTP_FROM_NAME
        value: TrueMatch
      - key: EMAIL_VERIFICATION_TOKEN_EXPIRES_HOURS
        value: 720
      - key: EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS
        value: 60
      - key: CLOUDINARY_CLOUD_NAME
        value: dykntxvyw
      - key: CLOUDINARY_API_KEY
        value: 367258928425611
      - key: CLOUDINARY_API_SECRET
        value: eGs2tcXDwVRW3v0sCUszBdBxY-A
