export const APPLICATION_STATUS = {
  APPLICATION_PENDING: 'APPLICATION_PENDING',
  SUBMITTED_TO_UNIVERSITY: 'SUBMITTED_TO_UNIVERSITY',
  UNDER_REVIEW: 'UNDER_REVIEW',
  OFFER_ISSUED: 'OFFER_ISSUED'
} as const;

export type ApplicationStatus = (typeof APPLICATION_STATUS)[keyof typeof APPLICATION_STATUS];

export const STATUS_STEPS: ApplicationStatus[] = [
  APPLICATION_STATUS.APPLICATION_PENDING,
  APPLICATION_STATUS.SUBMITTED_TO_UNIVERSITY,
  APPLICATION_STATUS.UNDER_REVIEW,
  APPLICATION_STATUS.OFFER_ISSUED
];